//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 10:00:54 PM ALMT 
//


package ru.sber.ekvit.service.soap.charge.wsdl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ru.sber.ekvit package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ru.sber.ekvit
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetChargesByAddressResponse }
     * 
     */
    public GetChargesByAddressResponse createGetChargesByAddressResponse() {
        return new GetChargesByAddressResponse();
    }

    /**
     * Create an instance of {@link GetChargesByAddressRequest }
     * 
     */
    public GetChargesByAddressRequest createGetChargesByAddressRequest() {
        return new GetChargesByAddressRequest();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

}
