//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.17 at 10:00:54 PM ALMT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://ekvit.sber.ru")
package ru.sber.ekvit.service.soap.charge.wsdl;
